from textual.app import App
from textual.theme import Theme

DEFAULT_THEME = "chess-green"

CHESS_VARIABLE_DEFAULTS: dict[str, str] = {
    "chess-coords": "#9aa4a6",
    "chess-border": "#19d66b",
    "chess-board-light": "#111718",
    "chess-board-dark": "#0c1213",
    "chess-empty-light": "#314043",
    "chess-empty-dark": "#263234",
    "chess-piece-white": "#e8ecec",
    "chess-piece-black": "#b4bcbc",
}

SEMANTIC_SUCCESS = "#19d66b"
SEMANTIC_WARNING = "#ffb000"
SEMANTIC_ERROR = "#ff4d4d"

CHESS_THEMES: dict[str, Theme] = {
    "chess-green": Theme(
        name="chess-green",
        primary="#19d66b",
        secondary="#9aa4a6",
        accent="#19d66b",
        foreground="#e8ecec",
        background="#0b0f10",
        surface="#111718",
        panel="#0c1213",
        success=SEMANTIC_SUCCESS,
        warning=SEMANTIC_WARNING,
        error=SEMANTIC_ERROR,
        dark=True,
        variables={
            "border": "#19d66b",
            "footer-background": "#0c1213",
            "footer-key-foreground": "#19d66b",
            "input-selection-background": "#19d66b 30%",
            "chess-coords": "#9aa4a6",
            "chess-border": "#19d66b",
            "chess-board-light": "#111718",
            "chess-board-dark": "#0c1213",
            "chess-empty-light": "#314043",
            "chess-empty-dark": "#263234",
            "chess-piece-white": "#e8ecec",
            "chess-piece-black": "#b4bcbc",
        },
    ),
    "chess-gray": Theme(
        name="chess-gray",
        primary="#b7bec0",
        secondary="#9aa4a6",
        accent="#b7bec0",
        foreground="#f0f5f5",
        background="#0b0f10",
        surface="#111718",
        panel="#0c1213",
        success=SEMANTIC_SUCCESS,
        warning=SEMANTIC_WARNING,
        error=SEMANTIC_ERROR,
        dark=True,
        variables={
            "border": "#b7bec0",
            "footer-background": "#0c1213",
            "footer-key-foreground": "#b7bec0",
            "input-selection-background": "#b7bec0 25%",
            "chess-coords": "#9aa4a6",
            "chess-border": "#b7bec0",
            "chess-board-light": "#111718",
            "chess-board-dark": "#0c1213",
            "chess-empty-light": "#2f3c3e",
            "chess-empty-dark": "#222c2e",
            "chess-piece-white": "#f0f5f5",
            "chess-piece-black": "#c6cccc",
        },
    ),
    "chess-amber": Theme(
        name="chess-amber",
        primary="#ffb000",
        secondary="#d2b57e",
        accent="#ffb000",
        foreground="#ffe2a8",
        background="#0d0b07",
        surface="#141007",
        panel="#100c05",
        success=SEMANTIC_SUCCESS,
        warning=SEMANTIC_WARNING,
        error=SEMANTIC_ERROR,
        dark=True,
        variables={
            "border": "#ffb000",
            "footer-background": "#100c05",
            "footer-key-foreground": "#ffb000",
            "input-selection-background": "#ffb000 25%",
            "chess-coords": "#d2b57e",
            "chess-border": "#ffb000",
            "chess-board-light": "#141007",
            "chess-board-dark": "#100c05",
            "chess-empty-light": "#4a3a1f",
            "chess-empty-dark": "#3b2f19",
            "chess-piece-white": "#ffe2a8",
            "chess-piece-black": "#f5c46a",
        },
    ),
    "chess-cyan": Theme(
        name="chess-cyan",
        primary="#2ee6d6",
        secondary="#93a9ad",
        accent="#2ee6d6",
        foreground="#e6fffd",
        background="#071012",
        surface="#0d1c1f",
        panel="#071417",
        success=SEMANTIC_SUCCESS,
        warning=SEMANTIC_WARNING,
        error=SEMANTIC_ERROR,
        dark=True,
        variables={
            "border": "#2ee6d6",
            "footer-background": "#071417",
            "footer-key-foreground": "#2ee6d6",
            "input-selection-background": "#2ee6d6 25%",
            "chess-coords": "#93a9ad",
            "chess-border": "#2ee6d6",
            "chess-board-light": "#0d1c1f",
            "chess-board-dark": "#071417",
            "chess-empty-light": "#3e666b",
            "chess-empty-dark": "#2f5256",
            "chess-piece-white": "#e6fffd",
            "chess-piece-black": "#bfe9e6",
        },
    ),
    "chess-blue": Theme(
        name="chess-blue",
        primary="#4aa3ff",
        secondary="#98a6bf",
        accent="#4aa3ff",
        foreground="#eef4ff",
        background="#070b12",
        surface="#101a2a",
        panel="#0a1220",
        success=SEMANTIC_SUCCESS,
        warning=SEMANTIC_WARNING,
        error=SEMANTIC_ERROR,
        dark=True,
        variables={
            "border": "#4aa3ff",
            "footer-background": "#0a1220",
            "footer-key-foreground": "#4aa3ff",
            "input-selection-background": "#4aa3ff 22%",
            "chess-coords": "#98a6bf",
            "chess-border": "#4aa3ff",
            "chess-board-light": "#101a2a",
            "chess-board-dark": "#0a1220",
            "chess-empty-light": "#3b4f73",
            "chess-empty-dark": "#2f405f",
            "chess-piece-white": "#eef4ff",
            "chess-piece-black": "#cbd7f2",
        },
    ),
    "chess-purple": Theme(
        name="chess-purple",
        primary="#c86bff",
        secondary="#b5a1c4",
        accent="#c86bff",
        foreground="#f6eaff",
        background="#0e0712",
        surface="#1b0f24",
        panel="#120a1a",
        success=SEMANTIC_SUCCESS,
        warning=SEMANTIC_WARNING,
        error=SEMANTIC_ERROR,
        dark=True,
        variables={
            "border": "#c86bff",
            "footer-background": "#120a1a",
            "footer-key-foreground": "#c86bff",
            "input-selection-background": "#c86bff 20%",
            "chess-coords": "#b5a1c4",
            "chess-border": "#c86bff",
            "chess-board-light": "#1b0f24",
            "chess-board-dark": "#120a1a",
            "chess-empty-light": "#6c4a86",
            "chess-empty-dark": "#573a70",
            "chess-piece-white": "#f6eaff",
            "chess-piece-black": "#dcc3ee",
        },
    ),
    "chess-red": Theme(
        name="chess-red",
        primary="#ff4d4d",
        secondary="#c2a0a0",
        accent="#ff4d4d",
        foreground="#fff0f0",
        background="#120707",
        surface="#241010",
        panel="#180a0a",
        success=SEMANTIC_SUCCESS,
        warning=SEMANTIC_WARNING,
        error=SEMANTIC_ERROR,
        dark=True,
        variables={
            "border": "#ff4d4d",
            "footer-background": "#180a0a",
            "footer-key-foreground": "#ff4d4d",
            "input-selection-background": "#ff4d4d 22%",
            "chess-coords": "#c2a0a0",
            "chess-border": "#ff4d4d",
            "chess-board-light": "#241010",
            "chess-board-dark": "#180a0a",
            "chess-empty-light": "#7a3c3c",
            "chess-empty-dark": "#673131",
            "chess-piece-white": "#fff0f0",
            "chess-piece-black": "#f0c6c6",
        },
    ),
    "chess-solarized": Theme(
        name="chess-solarized",
        primary="#2aa198",
        secondary="#93a1a1",
        accent="#2aa198",
        foreground="#eee8d5",
        background="#002b36",
        surface="#073642",
        panel="#002b36",
        success=SEMANTIC_SUCCESS,
        warning=SEMANTIC_WARNING,
        error=SEMANTIC_ERROR,
        dark=True,
        variables={
            "border": "#2aa198",
            "footer-background": "#073642",
            "footer-key-foreground": "#2aa198",
            "input-selection-background": "#2aa198 25%",
            "chess-coords": "#93a1a1",
            "chess-border": "#2aa198",
            "chess-board-light": "#073642",
            "chess-board-dark": "#002b36",
            "chess-empty-light": "#586e75",
            "chess-empty-dark": "#465a61",
            "chess-piece-white": "#eee8d5",
            "chess-piece-black": "#b7c3b0",
        },
    ),
    "chess-paper": Theme(
        name="chess-paper",
        primary="#7A4419",
        secondary="#515A47",
        accent="#7A4419",
        foreground="#2C1320",
        background="#f3f1e6",
        surface="#ffffff",
        panel="#efe8d6",
        success="#2f8f57",
        warning="#b87800",
        error="#b63a3a",
        dark=False,
        variables={
            "border": "#7A4419",
            "footer-background": "#efe8d6",
            "footer-key-foreground": "#7A4419",
            "input-selection-background": "#7A4419 18%",
            "chess-coords": "#515A47",
            "chess-border": "#7A4419",
            "chess-board-light": "#ffffff",
            "chess-board-dark": "#efe8d6",
            "chess-empty-light": "#b3ada0",
            "chess-empty-dark": "#9f988a",
            "chess-piece-white": "#2C1320",
            "chess-piece-black": "#333333",
        },
    ),
}


def register_chess_themes(app: App[None]) -> None:
    for theme in CHESS_THEMES.values():
        app.register_theme(theme)
