from textual.app import App
from textual.theme import Theme

DEFAULT_THEME = "chess-green"

CHESS_VARIABLE_DEFAULTS: dict[str, str] = {
    "chess-coords": "#9aa4a6",
    "chess-border": "#19d66b",
    "chess-board-light": "#111718",
    "chess-board-dark": "#0c1213",
    "chess-empty-light": "#314043",
    "chess-empty-dark": "#263234",
    "chess-piece-white": "#e8ecec",
    "chess-piece-black": "#b4bcbc",
    "chess-highlight-candidate": "#39ff88",
    "chess-highlight-last": "#ffd166",
    "chess-highlight-capture": "#ff5f6d",
    "chess-highlight-check": "#ff335f",
    "chess-feedback-action": "#39ff88",
    "chess-feedback-info": "#8fdfff",
    "chess-feedback-error": "#ff5f6d",
}

SEMANTIC_SUCCESS = "#19d66b"
SEMANTIC_WARNING = "#ffb000"
SEMANTIC_ERROR = "#ff4d4d"

CHESS_THEMES: dict[str, Theme] = {
    "chess-green": Theme(
        name="chess-green",
        primary="#19d66b",
        secondary="#9aa4a6",
        accent="#19d66b",
        foreground="#e8ecec",
        background="#0b0f10",
        surface="#111718",
        panel="#0c1213",
        success=SEMANTIC_SUCCESS,
        warning=SEMANTIC_WARNING,
        error=SEMANTIC_ERROR,
        dark=True,
        variables={
            "border": "#19d66b",
            "footer-background": "#0c1213",
            "footer-key-foreground": "#19d66b",
            "input-selection-background": "#19d66b 30%",
            "chess-coords": "#9aa4a6",
            "chess-border": "#19d66b",
            "chess-board-light": "#111718",
            "chess-board-dark": "#0c1213",
            "chess-empty-light": "#314043",
            "chess-empty-dark": "#263234",
            "chess-piece-white": "#e8ecec",
            "chess-piece-black": "#b4bcbc",
            "chess-highlight-candidate": "#39ff88",
            "chess-highlight-last": "#ffe066",
            "chess-highlight-capture": "#ff5f6d",
            "chess-highlight-check": "#ff335f",
            "chess-feedback-action": "#39ff88",
            "chess-feedback-info": "#8fdfff",
            "chess-feedback-error": "#ff5f6d",
        },
    ),
    "chess-gray": Theme(
        name="chess-gray",
        primary="#b7bec0",
        secondary="#9aa4a6",
        accent="#b7bec0",
        foreground="#f0f5f5",
        background="#0b0f10",
        surface="#111718",
        panel="#0c1213",
        success=SEMANTIC_SUCCESS,
        warning=SEMANTIC_WARNING,
        error=SEMANTIC_ERROR,
        dark=True,
        variables={
            "border": "#b7bec0",
            "footer-background": "#0c1213",
            "footer-key-foreground": "#b7bec0",
            "input-selection-background": "#b7bec0 25%",
            "chess-coords": "#9aa4a6",
            "chess-border": "#b7bec0",
            "chess-board-light": "#111718",
            "chess-board-dark": "#0c1213",
            "chess-empty-light": "#2f3c3e",
            "chess-empty-dark": "#222c2e",
            "chess-piece-white": "#f0f5f5",
            "chess-piece-black": "#c6cccc",
            "chess-highlight-candidate": "#f0f6f6",
            "chess-highlight-last": "#ffd166",
            "chess-highlight-capture": "#ff6b6b",
            "chess-highlight-check": "#ff335f",
            "chess-feedback-action": "#dce4e4",
            "chess-feedback-info": "#a8d8ff",
            "chess-feedback-error": "#ff6b6b",
        },
    ),
    "chess-amber": Theme(
        name="chess-amber",
        primary="#ffb000",
        secondary="#d2b57e",
        accent="#ffb000",
        foreground="#ffe2a8",
        background="#0d0b07",
        surface="#141007",
        panel="#100c05",
        success=SEMANTIC_SUCCESS,
        warning=SEMANTIC_WARNING,
        error=SEMANTIC_ERROR,
        dark=True,
        variables={
            "border": "#ffb000",
            "footer-background": "#100c05",
            "footer-key-foreground": "#ffb000",
            "input-selection-background": "#ffb000 25%",
            "chess-coords": "#d2b57e",
            "chess-border": "#ffb000",
            "chess-board-light": "#141007",
            "chess-board-dark": "#100c05",
            "chess-empty-light": "#4a3a1f",
            "chess-empty-dark": "#3b2f19",
            "chess-piece-white": "#ffe2a8",
            "chess-piece-black": "#f5c46a",
            "chess-highlight-candidate": "#ffe082",
            "chess-highlight-last": "#ffffff",
            "chess-highlight-capture": "#ff6b57",
            "chess-highlight-check": "#ff3b30",
            "chess-feedback-action": "#ffe082",
            "chess-feedback-info": "#f8c56b",
            "chess-feedback-error": "#ff6b57",
        },
    ),
    "chess-cyan": Theme(
        name="chess-cyan",
        primary="#2ee6d6",
        secondary="#93a9ad",
        accent="#2ee6d6",
        foreground="#e6fffd",
        background="#071012",
        surface="#0d1c1f",
        panel="#071417",
        success=SEMANTIC_SUCCESS,
        warning=SEMANTIC_WARNING,
        error=SEMANTIC_ERROR,
        dark=True,
        variables={
            "border": "#2ee6d6",
            "footer-background": "#071417",
            "footer-key-foreground": "#2ee6d6",
            "input-selection-background": "#2ee6d6 25%",
            "chess-coords": "#93a9ad",
            "chess-border": "#2ee6d6",
            "chess-board-light": "#0d1c1f",
            "chess-board-dark": "#071417",
            "chess-empty-light": "#3e666b",
            "chess-empty-dark": "#2f5256",
            "chess-piece-white": "#e6fffd",
            "chess-piece-black": "#bfe9e6",
            "chess-highlight-candidate": "#73fff2",
            "chess-highlight-last": "#ffe66d",
            "chess-highlight-capture": "#ff6b8a",
            "chess-highlight-check": "#ff3366",
            "chess-feedback-action": "#73fff2",
            "chess-feedback-info": "#a9f8ff",
            "chess-feedback-error": "#ff6b8a",
        },
    ),
    "chess-blue": Theme(
        name="chess-blue",
        primary="#4aa3ff",
        secondary="#98a6bf",
        accent="#4aa3ff",
        foreground="#eef4ff",
        background="#070b12",
        surface="#101a2a",
        panel="#0a1220",
        success=SEMANTIC_SUCCESS,
        warning=SEMANTIC_WARNING,
        error=SEMANTIC_ERROR,
        dark=True,
        variables={
            "border": "#4aa3ff",
            "footer-background": "#0a1220",
            "footer-key-foreground": "#4aa3ff",
            "input-selection-background": "#4aa3ff 22%",
            "chess-coords": "#98a6bf",
            "chess-border": "#4aa3ff",
            "chess-board-light": "#101a2a",
            "chess-board-dark": "#0a1220",
            "chess-empty-light": "#3b4f73",
            "chess-empty-dark": "#2f405f",
            "chess-piece-white": "#eef4ff",
            "chess-piece-black": "#cbd7f2",
            "chess-highlight-candidate": "#8fc7ff",
            "chess-highlight-last": "#ffd166",
            "chess-highlight-capture": "#ff6b7a",
            "chess-highlight-check": "#ff335f",
            "chess-feedback-action": "#8fc7ff",
            "chess-feedback-info": "#b8d8ff",
            "chess-feedback-error": "#ff6b7a",
        },
    ),
    "chess-purple": Theme(
        name="chess-purple",
        primary="#c86bff",
        secondary="#b5a1c4",
        accent="#c86bff",
        foreground="#f6eaff",
        background="#0e0712",
        surface="#1b0f24",
        panel="#120a1a",
        success=SEMANTIC_SUCCESS,
        warning=SEMANTIC_WARNING,
        error=SEMANTIC_ERROR,
        dark=True,
        variables={
            "border": "#c86bff",
            "footer-background": "#120a1a",
            "footer-key-foreground": "#c86bff",
            "input-selection-background": "#c86bff 20%",
            "chess-coords": "#b5a1c4",
            "chess-border": "#c86bff",
            "chess-board-light": "#1b0f24",
            "chess-board-dark": "#120a1a",
            "chess-empty-light": "#6c4a86",
            "chess-empty-dark": "#573a70",
            "chess-piece-white": "#f6eaff",
            "chess-piece-black": "#dcc3ee",
            "chess-highlight-candidate": "#e3a4ff",
            "chess-highlight-last": "#ffd166",
            "chess-highlight-capture": "#ff6b9a",
            "chess-highlight-check": "#ff3377",
            "chess-feedback-action": "#e3a4ff",
            "chess-feedback-info": "#d7b8ff",
            "chess-feedback-error": "#ff6b9a",
        },
    ),
    "chess-red": Theme(
        name="chess-red",
        primary="#ff4d4d",
        secondary="#c2a0a0",
        accent="#ff4d4d",
        foreground="#fff0f0",
        background="#120707",
        surface="#241010",
        panel="#180a0a",
        success=SEMANTIC_SUCCESS,
        warning=SEMANTIC_WARNING,
        error=SEMANTIC_ERROR,
        dark=True,
        variables={
            "border": "#ff4d4d",
            "footer-background": "#180a0a",
            "footer-key-foreground": "#ff4d4d",
            "input-selection-background": "#ff4d4d 22%",
            "chess-coords": "#c2a0a0",
            "chess-border": "#ff4d4d",
            "chess-board-light": "#241010",
            "chess-board-dark": "#180a0a",
            "chess-empty-light": "#7a3c3c",
            "chess-empty-dark": "#673131",
            "chess-piece-white": "#fff0f0",
            "chess-piece-black": "#f0c6c6",
            "chess-highlight-candidate": "#ffb3b3",
            "chess-highlight-last": "#ffd166",
            "chess-highlight-capture": "#ffffff",
            "chess-highlight-check": "#ffffff",
            "chess-feedback-action": "#ffb3b3",
            "chess-feedback-info": "#ffd0d0",
            "chess-feedback-error": "#ffffff",
        },
    ),
    "chess-solarized": Theme(
        name="chess-solarized",
        primary="#2aa198",
        secondary="#93a1a1",
        accent="#2aa198",
        foreground="#eee8d5",
        background="#002b36",
        surface="#073642",
        panel="#002b36",
        success=SEMANTIC_SUCCESS,
        warning=SEMANTIC_WARNING,
        error=SEMANTIC_ERROR,
        dark=True,
        variables={
            "border": "#2aa198",
            "footer-background": "#073642",
            "footer-key-foreground": "#2aa198",
            "input-selection-background": "#2aa198 25%",
            "chess-coords": "#93a1a1",
            "chess-border": "#2aa198",
            "chess-board-light": "#073642",
            "chess-board-dark": "#002b36",
            "chess-empty-light": "#586e75",
            "chess-empty-dark": "#465a61",
            "chess-piece-white": "#eee8d5",
            "chess-piece-black": "#b7c3b0",
            "chess-highlight-candidate": "#2de0c8",
            "chess-highlight-last": "#fdf6a3",
            "chess-highlight-capture": "#ff6b6b",
            "chess-highlight-check": "#ff3366",
            "chess-feedback-action": "#2de0c8",
            "chess-feedback-info": "#9ee8df",
            "chess-feedback-error": "#ff6b6b",
        },
    ),
    "chess-nord": Theme(
        name="chess-nord",
        primary="#88c0d0",
        secondary="#a7b5c5",
        accent="#88c0d0",
        foreground="#eceff4",
        background="#2e3440",
        surface="#3b4252",
        panel="#2b303b",
        success="#a3be8c",
        warning="#ebcb8b",
        error="#bf616a",
        dark=True,
        variables={
            "border": "#88c0d0",
            "footer-background": "#2b303b",
            "footer-key-foreground": "#88c0d0",
            "input-selection-background": "#88c0d0 24%",
            "chess-coords": "#a7b5c5",
            "chess-border": "#88c0d0",
            "chess-board-light": "#3b4252",
            "chess-board-dark": "#2b303b",
            "chess-empty-light": "#5e6b7e",
            "chess-empty-dark": "#4c566a",
            "chess-piece-white": "#eceff4",
            "chess-piece-black": "#d8dee9",
            "chess-highlight-candidate": "#a3be8c",
            "chess-highlight-last": "#ebcb8b",
            "chess-highlight-capture": "#bf616a",
            "chess-highlight-check": "#d08770",
            "chess-feedback-action": "#a3be8c",
            "chess-feedback-info": "#8fbcbb",
            "chess-feedback-error": "#bf616a",
        },
    ),
    "chess-dracula": Theme(
        name="chess-dracula",
        primary="#bd93f9",
        secondary="#a9a1b8",
        accent="#bd93f9",
        foreground="#f8f8f2",
        background="#282a36",
        surface="#343746",
        panel="#21222c",
        success="#50fa7b",
        warning="#f1fa8c",
        error="#ff5555",
        dark=True,
        variables={
            "border": "#bd93f9",
            "footer-background": "#21222c",
            "footer-key-foreground": "#bd93f9",
            "input-selection-background": "#bd93f9 24%",
            "chess-coords": "#a9a1b8",
            "chess-border": "#bd93f9",
            "chess-board-light": "#343746",
            "chess-board-dark": "#21222c",
            "chess-empty-light": "#6272a4",
            "chess-empty-dark": "#4d5a83",
            "chess-piece-white": "#f8f8f2",
            "chess-piece-black": "#d6ccff",
            "chess-highlight-candidate": "#50fa7b",
            "chess-highlight-last": "#f1fa8c",
            "chess-highlight-capture": "#ff79c6",
            "chess-highlight-check": "#ff5555",
            "chess-feedback-action": "#50fa7b",
            "chess-feedback-info": "#8be9fd",
            "chess-feedback-error": "#ff5555",
        },
    ),
    "chess-gruvbox": Theme(
        name="chess-gruvbox",
        primary="#fabd2f",
        secondary="#a89984",
        accent="#fabd2f",
        foreground="#ebdbb2",
        background="#282828",
        surface="#3c3836",
        panel="#1d2021",
        success="#b8bb26",
        warning="#fabd2f",
        error="#fb4934",
        dark=True,
        variables={
            "border": "#d79921",
            "footer-background": "#1d2021",
            "footer-key-foreground": "#fabd2f",
            "input-selection-background": "#fabd2f 22%",
            "chess-coords": "#a89984",
            "chess-border": "#d79921",
            "chess-board-light": "#3c3836",
            "chess-board-dark": "#1d2021",
            "chess-empty-light": "#665c54",
            "chess-empty-dark": "#504945",
            "chess-piece-white": "#fbf1c7",
            "chess-piece-black": "#d5c4a1",
            "chess-highlight-candidate": "#b8bb26",
            "chess-highlight-last": "#fabd2f",
            "chess-highlight-capture": "#fe8019",
            "chess-highlight-check": "#fb4934",
            "chess-feedback-action": "#b8bb26",
            "chess-feedback-info": "#83a598",
            "chess-feedback-error": "#fb4934",
        },
    ),
    "chess-rose-pine": Theme(
        name="chess-rose-pine",
        primary="#c4a7e7",
        secondary="#908caa",
        accent="#c4a7e7",
        foreground="#e0def4",
        background="#191724",
        surface="#26233a",
        panel="#1f1d2e",
        success="#9ccfd8",
        warning="#f6c177",
        error="#eb6f92",
        dark=True,
        variables={
            "border": "#c4a7e7",
            "footer-background": "#1f1d2e",
            "footer-key-foreground": "#c4a7e7",
            "input-selection-background": "#c4a7e7 22%",
            "chess-coords": "#908caa",
            "chess-border": "#c4a7e7",
            "chess-board-light": "#26233a",
            "chess-board-dark": "#1f1d2e",
            "chess-empty-light": "#524f67",
            "chess-empty-dark": "#403d52",
            "chess-piece-white": "#e0def4",
            "chess-piece-black": "#d7c7f7",
            "chess-highlight-candidate": "#9ccfd8",
            "chess-highlight-last": "#f6c177",
            "chess-highlight-capture": "#ebbcba",
            "chess-highlight-check": "#eb6f92",
            "chess-feedback-action": "#9ccfd8",
            "chess-feedback-info": "#31748f",
            "chess-feedback-error": "#eb6f92",
        },
    ),
    "chess-forest": Theme(
        name="chess-forest",
        primary="#8fbc8f",
        secondary="#9bb09b",
        accent="#8fbc8f",
        foreground="#e7f4df",
        background="#0b130d",
        surface="#162219",
        panel="#101911",
        success="#8fbc8f",
        warning="#d9c56c",
        error="#e36b63",
        dark=True,
        variables={
            "border": "#6fa56f",
            "footer-background": "#101911",
            "footer-key-foreground": "#8fbc8f",
            "input-selection-background": "#8fbc8f 24%",
            "chess-coords": "#9bb09b",
            "chess-border": "#6fa56f",
            "chess-board-light": "#162219",
            "chess-board-dark": "#101911",
            "chess-empty-light": "#40573d",
            "chess-empty-dark": "#30442f",
            "chess-piece-white": "#e7f4df",
            "chess-piece-black": "#c2d6b9",
            "chess-highlight-candidate": "#a7d98f",
            "chess-highlight-last": "#d9c56c",
            "chess-highlight-capture": "#e36b63",
            "chess-highlight-check": "#ff4d4d",
            "chess-feedback-action": "#a7d98f",
            "chess-feedback-info": "#9fd0b0",
            "chess-feedback-error": "#e36b63",
        },
    ),
    "chess-coffee": Theme(
        name="chess-coffee",
        primary="#d6a86e",
        secondary="#a9927d",
        accent="#d6a86e",
        foreground="#f4e7d3",
        background="#120c08",
        surface="#21160f",
        panel="#1a110c",
        success="#9bbb6d",
        warning="#d6a86e",
        error="#d66f5f",
        dark=True,
        variables={
            "border": "#b98955",
            "footer-background": "#1a110c",
            "footer-key-foreground": "#d6a86e",
            "input-selection-background": "#d6a86e 22%",
            "chess-coords": "#a9927d",
            "chess-border": "#b98955",
            "chess-board-light": "#21160f",
            "chess-board-dark": "#1a110c",
            "chess-empty-light": "#6b4b32",
            "chess-empty-dark": "#533924",
            "chess-piece-white": "#f4e7d3",
            "chess-piece-black": "#d9c0a2",
            "chess-highlight-candidate": "#c9d36a",
            "chess-highlight-last": "#f4c27d",
            "chess-highlight-capture": "#e38a65",
            "chess-highlight-check": "#e15b52",
            "chess-feedback-action": "#c9d36a",
            "chess-feedback-info": "#d6a86e",
            "chess-feedback-error": "#e38a65",
        },
    ),
    "chess-royal": Theme(
        name="chess-royal",
        primary="#ffd700",
        secondary="#aab2d5",
        accent="#ffd700",
        foreground="#f7f2d0",
        background="#070b1f",
        surface="#101842",
        panel="#0b1230",
        success="#7fd88f",
        warning="#ffd700",
        error="#ff5f6d",
        dark=True,
        variables={
            "border": "#ffd700",
            "footer-background": "#0b1230",
            "footer-key-foreground": "#ffd700",
            "input-selection-background": "#ffd700 20%",
            "chess-coords": "#aab2d5",
            "chess-border": "#ffd700",
            "chess-board-light": "#101842",
            "chess-board-dark": "#0b1230",
            "chess-empty-light": "#40508a",
            "chess-empty-dark": "#2d3a6b",
            "chess-piece-white": "#fff8d6",
            "chess-piece-black": "#d7ddff",
            "chess-highlight-candidate": "#7fd88f",
            "chess-highlight-last": "#ffd700",
            "chess-highlight-capture": "#ff8c42",
            "chess-highlight-check": "#ff5f6d",
            "chess-feedback-action": "#7fd88f",
            "chess-feedback-info": "#90d7ff",
            "chess-feedback-error": "#ff5f6d",
        },
    ),
    "chess-paper": Theme(
        name="chess-paper",
        primary="#7A4419",
        secondary="#515A47",
        accent="#7A4419",
        foreground="#2C1320",
        background="#f3f1e6",
        surface="#ffffff",
        panel="#efe8d6",
        success="#2f8f57",
        warning="#b87800",
        error="#b63a3a",
        dark=False,
        variables={
            "border": "#7A4419",
            "footer-background": "#efe8d6",
            "footer-key-foreground": "#7A4419",
            "input-selection-background": "#7A4419 18%",
            "chess-coords": "#515A47",
            "chess-border": "#7A4419",
            "chess-board-light": "#ffffff",
            "chess-board-dark": "#efe8d6",
            "chess-empty-light": "#b3ada0",
            "chess-empty-dark": "#9f988a",
            "chess-piece-white": "#2C1320",
            "chess-piece-black": "#333333",
            "chess-highlight-candidate": "#157a3f",
            "chess-highlight-last": "#a45d00",
            "chess-highlight-capture": "#b3202a",
            "chess-highlight-check": "#8f1020",
            "chess-feedback-action": "#157a3f",
            "chess-feedback-info": "#245c75",
            "chess-feedback-error": "#b3202a",
        },
    ),
    "chess-ice": Theme(
        name="chess-ice",
        primary="#0077aa",
        secondary="#5f7f8f",
        accent="#0077aa",
        foreground="#10202a",
        background="#eef8fb",
        surface="#ffffff",
        panel="#dceef4",
        success="#147a45",
        warning="#9a6a00",
        error="#b83f4b",
        dark=False,
        variables={
            "border": "#0077aa",
            "footer-background": "#dceef4",
            "footer-key-foreground": "#0077aa",
            "input-selection-background": "#0077aa 18%",
            "chess-coords": "#5f7f8f",
            "chess-border": "#0077aa",
            "chess-board-light": "#ffffff",
            "chess-board-dark": "#dceef4",
            "chess-empty-light": "#9ab8c5",
            "chess-empty-dark": "#82a6b5",
            "chess-piece-white": "#10202a",
            "chess-piece-black": "#263b45",
            "chess-highlight-candidate": "#147a45",
            "chess-highlight-last": "#9a6a00",
            "chess-highlight-capture": "#b83f4b",
            "chess-highlight-check": "#a1132a",
            "chess-feedback-action": "#147a45",
            "chess-feedback-info": "#0077aa",
            "chess-feedback-error": "#b83f4b",
        },
    ),
}


THEME_ORDER: tuple[str, ...] = tuple(CHESS_THEMES.keys())


def register_chess_themes(app: App[None]) -> None:
    for theme in CHESS_THEMES.values():
        app.register_theme(theme)


def next_chess_theme(current: str) -> str:
    if current not in THEME_ORDER:
        return DEFAULT_THEME

    index = THEME_ORDER.index(current)
    return THEME_ORDER[(index + 1) % len(THEME_ORDER)]
